name = "ci-dashboard"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]
main = ".svelte-kit/cloudflare/_worker.js"
workers_dev = false

[assets]
directory = ".svelte-kit/cloudflare"
binding = "ASSETS"

[vars]
GITHUB_OWNER = "darknight"
GITHUB_REPOS = "daily-digest,whoishiring-insight,ci-dashboard"
